cache: yarn
language: node_js

matrix:
  include:
  - node_js: '6.7'
    script:
      - yarn ci
      - yarn danger

  # Deployment related tasks
  - node_js: "node"
    script: ""  # NOOP as we don't need to run tests etc
    after_success: # This can never fail the build
      - nvm install 6.7 # Enforce the same version
      # Upload latest PR commit to S3
      - test ! $TRAVIS_PULL_REQUEST == "false" && scripts/deploy_commit.sh
      # Upload merges to master to apphub
      - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then scripts/deploy_apphub.sh

cache:
  yarn: true
  directories:
    - node_modules
    - .jest/cache
