name: Trigger beta iOS release

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/deploys/deploy-beta-ios

      - name: Trigger release
        # CircleCI doesn't automatically run builds on the beta branch (only main and PRs)
        # so this is a github action to force it to do so.
        run: |
          curl \
            -X POST \
            --header "Content-Type: application/json" \
            -d '{"branch": "beta-ios"}' \
            https://circleci.com/api/v1.1/project/github/artsy/eigen/build?circle-token=${{ secrets.CircleToken }}
