name: ☢️ Conventional Commits Check

on:
  pull_request:
    types: [edited, opened, ready_for_review, reopened]

jobs:
  run-conventional-commits-check:
    uses: artsy/duchamp/.github/workflows/conventional-commits-check.yml@main
